language: erlang

sudo: required

before_install:
  - sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 36A1D7869245C8950F966E92D8576A8BA88D21E9
  - sudo sh -c "echo deb https://apt.dockerproject.org/repo ubuntu-precise main > /etc/apt/sources.list.d/docker.list"
  - sudo apt-get update
  - sudo apt-get install docker-engine
  - sudo service docker start
  - sudo docker info
  - sudo -i; sudo curl -L https://github.com/docker/compose/releases/download/1.6.0/docker-compose-`uname -s`-`uname -m` > /usr/local/bin/docker-compose; sudo chmod +x /usr/local/bin/docker-compose

notifications:
  email: false

otp_release:
  - 18.1
  - 17.4
  - R16B03-1

script:
  - scripts/setup-1-node-test-env.sh
  - make deps
  - make test; TEST_RESULT=$?; if [ ! $TEST_RESULT -eq 0 ]; then cat logs/ct_run.test@*/*.brod.logs/run.*/suite.log; echo $TEST_RESULT; exit 1; fi
  - make xref
  - make docs
  - make escriptize
  - scripts/cli-produce-test.sh

