language: erlang

sudo: required

before_install:
  - sudo apt-key adv --keyserver hkp://p80.pool.sks-keyservers.net:80 --recv-keys 58118E89F3A912897C070ADBF76221572C52609D
  - sudo sh -c "echo deb https://apt.dockerproject.org/repo ubuntu-precise main > /etc/apt/sources.list.d/docker.list"
  - sudo apt-get update
  - sudo apt-get install docker-engine
  - sudo docker info
  - curl -L https://github.com/docker/compose/releases/download/1.6.0/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin/

notifications:
  email: false

otp_release:
  - 18.2.1
  - 17.5

script:
  - set -e
  - make vsn-check
  - scripts/line-width-check.sh
  - make deps
  - make app
  - make xref
  - make edoc
  - make distclean
  - echo "verifying rebar compilation"
  - rebar get-deps
  - rebar compile
  - rm rebar.lock # delete rebar.lock so it gets re-created, expecting no diff
  - make distclean
  - echo "verifying rebar3 compilation"
  - wget https://s3.amazonaws.com/rebar3/rebar3
  - chmod +x rebar3
  - ./rebar3 compile
  - DIFF=$(git diff rebar.lock); if [ -n "$DIFF" ]; then echo 'rebar.lock discrepancy'; exit 1; fi;
  - make distclean
  - make escript
  - make test-env
  - scripts/cli-produce-test.sh
  - make t

