language: erlang

sudo: required

env:
  BROD_CLI_PRODUCE_TEST_TOPIC: brod-cli-produce-test
  BROD_CLIENT_SUITE_TOPIC: brod-client-SUITE-topic
  BROD_PRODUCER_SUITE_TOPIC: brod_producer_SUITE

before_install:
  - sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 36A1D7869245C8950F966E92D8576A8BA88D21E9
  - sudo sh -c "echo deb https://get.docker.io/ubuntu docker main > /etc/apt/sources.list.d/docker.list"
  - sudo apt-get update
  - sudo apt-get install lxc-docker
  - sudo docker info
  - sudo docker pull spotify/kafka
  - sudo docker run --name kafka -d -p 2181:2181 -p 9092:9092 --env ADVERTISED_HOST="localhost" --env ADVERTISED_PORT=9092 spotify/kafka
  - sudo docker ps -a
  - n=0; while [ "$(sudo docker exec kafka bash -c '/opt/kafka*/bin/kafka-topics.sh --zookeeper localhost --list')" != '' ]; do if [ $n -gt 4 ]; then echo timeout; exit 1; fi; n=$(( n + 1 )); sleep 1; done
  - sudo docker exec kafka bash -c "/opt/kafka*/bin/kafka-topics.sh --zookeeper localhost --create --partitions 1 --replication-factor 1 --topic $BROD_CLI_PRODUCE_TEST_TOPIC"
  - sudo docker exec kafka bash -c "/opt/kafka*/bin/kafka-topics.sh --zookeeper localhost --create --partitions 1 --replication-factor 1 --topic $BROD_CLIENT_SUITE_TOPIC"
  - sudo docker exec kafka bash -c "/opt/kafka*/bin/kafka-topics.sh --zookeeper localhost --create --partitions 1 --replication-factor 1 --topic $BROD_PRODUCER_SUITE_TOPIC"

notifications:
  email: false

otp_release:
  - 18.1
  - 17.4
  - R16B03-1

script:
  - make deps
  - make test; TEST_RESULT=$?; if [ ! $TEST_RESULT -eq 0 ]; then cat logs/ct_run.test@*/*.brod.logs/run.*/suite.log; echo $TEST_RESULT; exit 1; fi
  - make xref
  - make docs
  - make escriptize
  - scripts/cli-produce-test.sh

