language: erlang

sudo: required

env:
  BROD_CLI_PRODUCE_TEST_TOPIC: brod-cli-produce-test

install:
  - sudo apt-get install -y linux-image-virtual kernel linux-image-extra-virtual
  - curl -sSL https://get.docker.com/ | sudo sh
  - sudo docker pull spotify/kafka
  - sudo docker --name kafka -d -p 2181:2181 -p 9092:9092 --env ADVERTISED_HOST="localhost" --env ADVERTISED_PORT=9092 spotify/kafka
  - sudo docker ps -a
  - sudo docker exec kafka bash -c "/opt/kafka*/bin/kafka-topics.sh --zookeeper localhost --create --partitions 1 --replication-factor 1 --topic $BROD_CLI_PRODUCE_TEST_TOPIC"

notifications:
  email: false

otp_release:
  - 18.1
  - 17.4
  - R16B03-1

script:
  - set -e
  - make test
  - make xref
  - make docs
  - make escriptize
  - scripts/cli-produce-test.sh

