sudo: required

services:
  - docker

env:
  BROD_CLI_PRODUCE_TEST_TOPIC: brod-cli-produce-test

language: erlang

before_install:
  - docker pull spotify/kafka
  - docker --name kafka -d -p 2181:2181 -p 9092:9092 --env ADVERTISED_HOST="localhost" --env ADVERTISED_PORT=9092 spotify/kafka
  - docker ps -a
  - docker exec kafka bash -c "/opt/kafka*/bin/kafka-topics.sh --zookeeper localhost --create --partitions 1 --replication-factor 1 --topic $BROD_CLI_PRODUCE_TEST_TOPIC"

notifications:
  email: false

otp_release:
  - 18.1
  - 17.4
  - R16B03-1
  - R15B03

script: "make test doc escriptize && scripts/cli-produce-test.sh"

